### PR TITLE
Makes the library inline with the Base Generator master version

### PR DESCRIPTION
**Pull request by sendilkumarn**
- [ ] Supports JHipster v 5.6
- [ ] Updates spring Boot to 2.0.6
- [ ] Updates Kotlin to v1.2.51 (since Spring 2.0.6 supports that)

### CODE REVIEW

**Comment by sendilkumarn** [comment]
@pascalgrimaud Any idea why Travis is failing?  Can you take a look?

**Comment by pascalgrimaud** [comment]
@sendilkumarn : I saw in Travis log:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/app/src/main/java/io/github/jhipster/sample/config/CacheConfiguration.java:[36,64] cannot find symbol
  symbol:   class UserRepository
  location: package io.github.jhipster.sample.repository
[ERROR] /home/travis/app/src/main/java/io/github/jhipster/sample/config/CacheConfiguration.java:[37,64] cannot find symbol
  symbol:   class UserRepository
  location: package io.github.jhipster.sample.repository
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:47 min
[INFO] Finished at: 2018-11-09T01:51:28+11:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (java-compile) on project jhipster-sample-application: Compilation failure: Compilation failure: 
[ERROR] /home/travis/app/src/main/java/io/github/jhipster/sample/config/CacheConfiguration.java:[36,64] cannot find symbol
[ERROR]   symbol:   class UserRepository
[ERROR]   location: package io.github.jhipster.sample.repository
[ERROR] /home/travis/app/src/main/java/io/github/jhipster/sample/config/CacheConfiguration.java:[37,64] cannot find symbol
[ERROR]   symbol:   class UserRepository
[ERROR]   location: package io.github.jhipster.sample.repository
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
mv: cannot stat target/*.war: No such file or directory
Error when packaging
```

**Comment by sendilkumarn** [comment]
Yeah I saw this too. But I am reusing this from the base-generator.

**Comment by pascalgrimaud** [comment]
@sendilkumarn : I'll have a look on it tonight, after my day work :)

**Comment by pascalgrimaud** [comment]
I think I solved the issue:
- update Travis builds
- fix issue in generator kotlin

I'll PR tomorrow morning

**Pull request merged**
