### PR TITLE
Upgrade to Node.js 12.16.0 LTS

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/pull/11328

### CODE REVIEW

**Comment by sendilkumarn** [comment]
Thanks @pascalgrimaud but sadly I think we have to wait until we support 6.7.1 here

**Comment by pascalgrimaud** [comment]
yes, no worry !!

**Comment by sendilkumarn** [comment]
Closed and re-opened the pull request to trigger CI builds again

**Comment by sendilkumarn** [comment]
@pascalgrimaud can you rebase please?

**Comment by pascalgrimaud** [comment]
@sendilkumarn : sorry, I can't until tonight. No computer with me right now. If it can wait... :)

**Comment by sendilkumarn** [comment]
Sure go for it :)

**Comment by pascalgrimaud** [comment]
rebase just done

**Pull request merged**
