### PR TITLE
CI: rename ngx-psql-es-noi18n to ngx-psql-es-noi18n-mapsid

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/pull/9094

### CODE REVIEW

**Comment by pvliss** [comment]
@sendilkumarn Can you please merge this otherwise the CI builds will be broken? Thanks!

@pascalgrimaud Should we also adapt the Travis and Azure builds to follow the changes you made in the parent JHipster as well?

**Comment by pvliss** [comment]
Apply same changes found in the following PRs mainly regarding JDK8 + JDK 11:
- https://github.com/jhipster/generator-jhipster/pull/9410
- https://github.com/jhipster/generator-jhipster/pull/9507
- https://github.com/jhipster/generator-jhipster/pull/9512

**Comment by pascalgrimaud** [comment]
Of course yes !!

**Comment by pvliss** [comment]
This PR can be closed as the change has already been merged as part of https://github.com/jhipster/jhipster-kotlin/pull/109/commits/e5b2bb5365ec56517ee32c7aac9f8aa0bd993c5f.

**Pull request closed without merging**
