### PR TITLE
Upgrade to Spring Boot 2.1

### PR DESCRIPTION
**Pull request by sendilkumarn**

### CODE REVIEW

**Comment by pvliss** [comment]
Hello @sendilkumarn . I have now switched my local branch to track changes on this upstream branch and I want to push the latest changes of the JHipster master in order to fix the compilation errors, but it seems that I do not have access:
```
pav@PAV-UBUNTU:jhipster-kotlin$ git push
Username for 'https://github.com': pvlissidis@gmail.com
Password for 'https://pvlissidis@gmail.com@github.com': 
remote: Permission to jhipster/jhipster-kotlin.git denied to pvliss.
fatal: unable to access 'https://github.com/jhipster/jhipster-kotlin/': The requested URL returned error: 403
```

Should I be granted access or create another PR? How will that work from now on? Sorry but I am not that familiar with Git and learning along the way

**Comment by sendilkumarn** [comment]
If you don't mind, we can create a PR for this branch? I will also do the same for future PRs. The amount of change is making it very difficult to verify them.

**Comment by pvliss** [comment]
I do not mind. So I just create a PR against this branch, right?

**Comment by sendilkumarn** [comment]
Yeah please

**Comment by sendilkumarn** [comment]
@pvliss Did you already start with Client?

**Comment by pvliss** [comment]
Yes. I have actually finished and wait for Travis CI to complete. See https://github.com/pvliss/jhipster-kotlin/tree/migrate-client-package

**Comment by pvliss** [comment]
@sendilkumarn So if I understand correctly you have created a new branch [sb21](https://github.com/jhipster/jhipster-kotlin/tree/sb21) and created a new PR #98 , so this one can be closed?

**Comment by sendilkumarn** [comment]
Closing this in favor of #98  (both are technically the same PR)

**Pull request closed without merging**
