### PR TITLE
Upgrade to Node 10.15.0

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Related to https://github.com/jhipster/generator-jhipster/pull/9052

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
The build failed because of migration to micrometer.
I'm opening a new ticket

**Comment by sendilkumarn** [comment]
Thanks @pascalgrimaud

**Comment by pvliss** [comment]
@sendilkumarn This has also been already applied as part of #83 in commit https://github.com/jhipster/jhipster-kotlin/commit/b1eb4c2367225cc91b74da8d7f63b485e49cbc86 . So I think it can be safely closed or merged

**Comment by sendilkumarn** [comment]
You are right @pvliss thanks

**Pull request closed without merging**
