### PR TITLE
#139 Convert usages of Optional to Kotlin nullables - WIP

### PR DESCRIPTION
**Pull request by kozub**
Hello Team, 

I'm creating a PR to present the progress in work on the issue. That changes allows to generate simple microservice with SQL database with Kotlin nullable instead of Optionals. 

I'm planning to continue work in next few days to cover features with required change. Please let me know what do you think about that approach. 

Please note that this code is not ready to merge!

### CODE REVIEW

**Comment by pvliss** [comment]
Nice work @kozub . You are definitely on the right path. Let us know when you are done or if you need any help

**Comment by sendilkumarn** [comment]
Thanks @kozub  please let me know once you have finished it. I will take a review. The builds are failing because of the recent JHipster release. Hopefully, #189 will fix it.

**Comment by kozub** [comment]
> Thanks a lot @kozub for the PR. Please let me know once you have finished it. I will take a review. The builds are failing because of the recent JHipster release. Hopefully, #189 will fix it.

Hey @sendilkumarn, thank you for your message. I was planning to ask you about that errors, because of fact that I was not able to reproduce it. 

Speaking about progress in the work, most of work is done. There are few classes that still uses Java's Optional:

- SpringSecurityAuditorAware.kt.ejs - it extends/implements AuditorAware
- SimpleAuthoritiesExtractor.kt.ejs - it extends/implements AuthoritiesExtractor
- AuditResource.kt.ejs and UserResource.kt.ejs - they use ResponseUtil.wrapOrNotFound() that comes from JHipster. We might consider to add Kotlin extension. I think that it might be done as separate story / PR.  Just to not overcomplicate that PR. 

Could you please rerun the builds after merging your fix? I expect that some of them will fail because of my changes, so I'm going to fix it and then I will squash commit and ask you for review.

**Comment by sendilkumarn** [comment]
Awesome, the main generator is updated can you please rebase. Sorry for the trouble let me know if you need any help.

**Comment by kozub** [comment]
> Awesome, the main generator is updated can you please rebase. Sorry for the trouble let me know if you need any help.

Thank you for your message. I will rebase my branch and continue work.

**Comment by sendilkumarn** [comment]
@kozub Do you plan to work on this? You are almost there, I think rebase and refactoring couple more files will finish this PR.

**Comment by kozub** [comment]
@sendilkumarn - Sorry for my late reply - I had quite busy time in last few. I will try to rebase it today.

**Comment by kozub** [comment]
> @sendilkumarn - Sorry for my late reply - I had quite busy time in last few. I will try to rebase it today.

@sendilkumarn -  Do you have any suggestions how to debug .ejs templates effectively? After rebase there are some syntax errors in UserService.kt.ejs but I could not figure out what is the problem. What kind of tools do you use for working with .ejs files? I've tried Intellij + EJS plugin, but unfortunately I does not discover syntax error.  

An error that I found:

`Error: Copying template src/main/kotlin/package/service/UserService.kt.ejs failed. [SyntaxError: Unexpected token catch in /Users/ME/github/jhipster-kotlin/generators/server/templates/src/main/kotlin/package/service/UserService.kt.ejs while compiling ejs`

**Comment by ruddell** [comment]
@kozub You can use [`ejs-lint`](https://www.npmjs.com/package/ejs-lint) to help find errors in `ejs` templates.

```
npx ejslint generators/**/*.ejs    
```
Returns:
```
Unexpected token (739:5) in generators/server/templates/src/main/kotlin/package/service/UserService.kt.ejs
```
Maybe an opening `{` was removed somewhere, or an extra `}` exists somewhere in the changes to `UserService.kt.ejs` (ejslint passes on master)

**Comment by sendilkumarn** [comment]
@kozub are you willing to complete this?

**Comment by sendilkumarn** [comment]
Closing this PR, It is stale for a while now. Thanks @kozub for spending time on this.

**Pull request closed without merging**
