### PR TITLE
Remove `val` usage in TokenProvider

### PR DESCRIPTION
**Pull request by emilpaw**
A part towards #306

### CODE REVIEW

**Comment by sendilkumarn** [comment]
Thanks @emilpaw for the contribution 🎉 

This looks good! I started the CI will merge it when it finishes.

**Comment by sendilkumarn** [comment]
@emilpaw  can you please take a look at the build? there are few failures..

**Comment by emilpaw** [comment]
@sendilkumarn Many of the failing tests have definitely nothing to do with my changes. e.g. all the React tests fail because of this issue: https://github.com/jhipster/jhipster-kotlin/issues/330
The ngx-gradle-fr test also fails because of some frontend related issue: https://github.com/jhipster/jhipster-kotlin/runs/5526701353?check_suite_focus=true

I'd like to wait until the issues are resolved before I continue to work on this PR.

**Comment by sendilkumarn** [comment]
Closing this in favor of #335

**Pull request closed without merging**
