### PR TITLE
Travis: fix configuration

### PR DESCRIPTION
**Pull request by pascalgrimaud**
It will only fix the Travis configuration:
- installation
- npm link
- template instead of copy

But there are some tests which failed:

```
[ERROR] Failures: 
[ERROR]   AccountResourceIntTest.testRegisterDuplicateEmail:400 Status expected:<201> but was:<400>
[ERROR]   AccountResourceIntTest.testRegisterDuplicateLogin:345 Status expected:<201> but was:<400>
[ERROR]   AccountResourceIntTest.testRegisterUppercaseEmail:205 expected:<"[j]oe@example.com"> but was:<"[J]oe@example.com">
[INFO] 
[ERROR] Tests run: 123, Failures: 3, Errors: 0, Skipped: 0
```

I think it is related to the recent change on AccountResource and UserService :
- https://github.com/jhipster/generator-jhipster/commit/7ac4ef08c68cdbd121053b00dc02541b3f5644e8#diff-0bf55514d0fa8723d3b403a7443c8705
- https://github.com/jhipster/generator-jhipster/commit/458f654e22c3eed92748d866bd14989a5cdbb09d#diff-eb8ab57e6c1b5729372ec3081226b95d

### CODE REVIEW

**Comment by sendilkumarn** [comment]
Can we use a particular version of JHipster here

For example, use only 5.3.0 JHipster rather than the master

**Comment by pascalgrimaud** [comment]
yes @sendilkumarn 
I will update this PR

**Comment by pascalgrimaud** [comment]
it will still fail, because of AccountResource integration tests 

we need to update AccountResource.kt and UserService.kt to be consistent with the java version, specially the recent change on lower cap login

it is released in v5.3.0

**Comment by sendilkumarn** [comment]
I have changed it in master. It should work now 👍

**Comment by pascalgrimaud** [comment]
you're right, it's green !

**Pull request merged**
