### PR TITLE
Feat/upgrade to jhipster 6.10.0

### PR DESCRIPTION
**Pull request by sendilkumarn**

### CODE REVIEW

**Comment by sendilkumarn** [comment]
The failure is due to a missing library. The current JHipster master also fails. @pascalgrimaud any idea?

**Comment by mraible** [comment]
@sendilkumarn [The error](https://github.com/jhipster/jhipster-kotlin/pull/241/checks?check_run_id=820396718#step:15:56) looks like it comes from Springfox and its dependency on `org.springframework.boot.experimental:spring-boot-autoconfigure-r2dbc:pom:0.1.0.M3`. Maybe you need to exclude it?

**Comment by sendilkumarn** [comment]
@mraible Yeah saw that, It is failing on the main generator too. Is this something we have to change everywhere?

**Comment by mraible** [comment]
I think r2dbc changed the coordinates of their starter (removing `experimental`). It might be something we have to ask the Springfox folks to change.

**Pull request merged**
