### PR TITLE
Update Copyright Headers for 2020

### PR DESCRIPTION
**Pull request by SudharakaP**
Related to https://github.com/jhipster/generator-jhipster/pull/11048

### CODE REVIEW

**Comment by SudharakaP** [comment]
@sendilkumarn: You are welcome :smile:

**Comment by sendilkumarn** [comment]
@SudharakaP Can you help to resolve the conflicts?

**Comment by SudharakaP** [comment]
Close/Open for tests.

**Comment by SudharakaP** [comment]
@sendilkumarn : I've resolved the conflicts. The travis build seem to fail since it was removed during the upgrade but GitHub doesn't remove it from the pull request. :smile:

**Comment by sendilkumarn** [comment]
This is interesting. I will merge this. Again thanks for the PR.

**Comment by SudharakaP** [comment]
You are welcome. :smile:

**Pull request merged**
