### PR TITLE
Update to Spring Boot 2.1

### PR DESCRIPTION
**Pull request by sendilkumarn**

### CODE REVIEW

**Comment by pvliss** [comment]
Hello @sendilkumarn. Just noticed that you squashed all commits into a single commit and all history is lost. Don't we need the history? I understand that some should be squashed to have a cleaner history but some might prove useful in the future while debugging/testing. Also many of the comments help to keep track of what has been migrated from the parent JHipster project.

**Comment by sendilkumarn** [comment]
@pvliss Yes, I too saw that. But can we aim for a cleaner (shorter) commits next time? 

I will see what I can do with respect to cleaning the commits if that might help.

**Comment by sendilkumarn** [comment]
@pvliss history restored :)

**Comment by pvliss** [comment]
Excellent!!! Thanks a lot @sendilkumarn !!!!

Yes, the history was a bit messy but the PR was open for ~3 months, was a lot of work and had many issues with React e2e tests so kind of expected. I believe from now on it will be cleaner and easier to follow

**Comment by pvliss** [comment]
Forgot to mention. Can you please also merge #106 to fix the CI again? Thanks

**Pull request merged**
